id: shopware_intro
learningObjectives:
  - Understand the benefits of Shopware and plugins
hints:
  - Think about how plugins can enhance the functionality of your store.
  - Consider the flexibility and scalability that Shopware offers.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Welcome to the world of Shopware! Today, we're diving into the realm of
              plugins and how they can supercharge your store.
          - text: Shopware is a powerful e-commerce platform that allows for extensive
              customization through plugins. These plugins can add new features,
              improve user experience, and streamline operations.
          - text: Let's get started by understanding what makes Shopware and its plugins so
              beneficial.
    - actionId: ready_message
      params:
        person: lucca
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: bot_message
        params:
          person: lucca
          messages:
            - text: Great! Now that you know why Shopware is awesome, let's move on to running
                your shop.
      - actionId: finish_step
