id: shopware_intro
learningObjectives:
  - Understand the benefits of Shopware and plugins
hints:
  - Think about how plugins can enhance the functionality of your store.
  - Consider the flexibility and scalability that Shopware offers.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Welcome to the world of Shopware! Today, we're diving into the realm of plugins and how they can supercharge your store.
          - text: Shopware is built with developers in mind - it uses modern PHP practices and provides a robust plugin system that lets you extend your shop without touching the core code.
          - text: Through plugins, you can add new features, integrate with other services, or customize how your shop works. That's what makes Shopware such a practical choice for building online stores.
          - text: Let's get started by understanding what makes Shopware and its plugins so beneficial.
    - actionId: ready_message
      params:
        person: lucca
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: bot_message
        params:
          person: lucca
          messages:
            - text: Great! Let's move on to running your shop.
      - actionId: finish_step
