id: install_custom_plugin
learningObjectives:
  - Install a custom plugin in Shopware
hints:
  - Navigate to Extensions > My extensions.
  - Find 'Plugin with custom storefront controller' and click 'Install'.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Time to :instruction[install our custom plugin]. This is a simple demo plugin that adds a random image link to product pages - it's designed to show you the basics of plugin development in Shopware.
          - text: While the functionality is basic, it demonstrates key concepts like custom controllers and template extensions.
          - text: Head over to Extensions > My extensions and find 'Plugin with custom storefront controller' in the list.
          - text: Click 'Install' to activate the plugin.
    - actionId: ready_message
      params:
        person: lucca
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: bot_message
        params:
          person: lucca
          messages:
            - text: Great! The demo plugin is now installed. This simple example will help us understand how Shopware plugins work before we create more complex ones.
      - actionId: finish_step
