id: customize_plugin
learningObjectives:
  - Customize the installed plugin and open a PR
hints:
  - Look for the image.html modal component in the plugin code
  - The product name should be passed to the modal title using the controller
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Let's improve the "View Image" functionality! When users click the "View Image" button, we want to show the product name in the modal's title.
          - text: You'll need to modify the modal component to pass and display the product name. Once you're done, open a pull request for review.
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    do:
      - actionId: github_pr_review
        params:
          messages:
            person: lucca
            approved: "Great job adding the product name to the modal title! You can now merge your changes."
